#-------------------------------
# Site Settings
title: Spookalucca.Games
logo: /images/Spookalucca_128_trans.png
description: SpookaLucca Games

#-------------------------------
# Navigation Settings
menu-settings:
  menu-items:
    - title: 'Home'
      url: '/'
    - title: 'About'
      url: '/about/'


#-------------------------------
# Author Settings
author:
  name: SpookaLucca
  avatar: '/images/Spookalucca_128_blk.png'


#-------------------------------
# Hero Settings
hero:
  title: SpookaLucca Games
  description: Home of Haunting Diversions
  image: '/images/607.jpg'

#-------------------------------
# Contact Settings
contact:
  email: contact@spookalucca.games 
  description: Send me a spooky missive from the void! # Contact me via Mailchimp

#-------------------------------
# Footer section
social:
- {icon: "fa-brands fa-paypal", name: "PayPal", link: "https://paypal.me/spookalucca"}
- {icon: "fa-brands fa-patreon", name: "Patreon", link: "https://patreon.com/spookalucca"}
- {icon: "fa-brands fa-bluesky", name: "Bluesky", link: "https://bsky.app/profile/spookalucca.bsky.social"} # Icon wasn't working for some reason
#- {icon: "fa-brands fa-instagram", name: "Instagram", link: "https://www.instagram.com/spookaluccagames/"} # Enable link once I start posting content
- {icon: "fa-brands fa-twitch", name: "Twitch", link: "https://www.twitch.tv/spookalucca"} # Enable link once I start streaming / making devlogs
- {icon: "fa-brands fa-youtube", name: "Youtube", link: "https://www.youtube.com/@spookalucca"} # Enable link once I start streaming / making devlogs
#- {icon: "fa-brands fa-discord", name: "Discord", link: "https://discord.com/"} # Enable link to page describing patreon-only Discord
#- {icon: "fa-brands fa-tiktok", name: "TikTok", link: "https://www.tiktok.com/@spookalucca"} # Enable link once I start posting content
#- {icon: "fa-brands fa-steam", name: "Steam", link: "https://store.steampowered.com"} # Enable link to developer page once that exists
#- {icon: "fa-brands fa-itch-io", name: "Itch.io", link: "https://spookalucca.itch.io/"} # Enable link once I have a game posted
# Other icons can be found at https://fontawesome.com/icons

#-------------------------------
# Newsletter
mailchimp: # To enable the mailchimp form, use the value 'enable'. To disable the form, leave the field blank.
mailchimp-identifier: games.us22.list-manage.com/subscribe/post?u=89585f67cb46417ecc4dc4936&amp;id=fb960542ea&amp;f_id=0025cce1f0 # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
mailchimp-button-text: Join
